### ISSUE TITLE
mu_PARAMETER estimates median, not mean

### ISSUE THREAD

**Issue by maxmantei** [CCS-Lab/hBayesDM#117] opened 2020-04-17 11:36 UTC
Hi!

This came up in a discussion on the Stan discourse page, so I just wanted to give a heads up.

In your **getting started** guide you state that

> Note that hyper (group) mean parameters are indicated by mu_PARAMETER (e.g., mu_xi, mu_ep, mu_rho).

and in the models you compute those as ``mu_PARAMETER = Phi_approx(mu_pr[PARAMETER_INDEX]) * scaling;`` in the generated quantities block. However, this will give you an estimate of the posterior _median_ of the group parameter, not the posterior _mean_.

If Y = _f_(X) and _f_ is non-linear, then E[Y] =/= _f_(E[X]), as E[_f_(X)] =/= _f_(E[X]) per [Jensen's inequality](https://en.wikipedia.org/wiki/Jensen%27s_inequality).

If the underlying distribution (for X) is _symmetric_, ``mu_PARAMETER`` (i.e. _f_(E[X])) will the parameter for the posterior _median_ of the group distribution.

Cheers!

**Comment by Nathaniel-Haines** [comment] 2020-07-03 03:24
Hi @maxmantei, thanks for the info! Can you link to the discourse discussion?

I guess I'm just wondering if this applies in our case. We are estimating the parameters using this scaling in the transformed parameters block, and then mirroring this in the generated quantities block. So, my understanding is that the expectation used in the likelihood is the same as in the generated quantities (i.e. we are not just transforming the parameter after fitting the model). 

Anyway, happy to look into this if it's indeed a problem!

**Comment by Nathaniel-Haines** [comment] 2023-05-27 15:26
Marked as duplicate of https://github.com/CCS-Lab/hBayesDM/issues/156, with solution linked in the newer issue 🤓

**Closed by Nathaniel-Haines** 2023-05-27 15:26 UTC
Labels: duplicate
